# Generated by Django 2.2.6 on 2019-10-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blogTitle', models.CharField(max_length=200)),
                ('blogText', models.TextField()),
                ('img', models.ImageField(default='', upload_to='blog/images')),
                ('blogDate', models.DateTimeField()),
            ],
        ),
    ]
